// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyProductAttribute("Fable.Formatting")>]
[<assembly: AssemblyDescriptionAttribute("A package of libraries for building great F# documentation, samples and blogs")>]
[<assembly: AssemblyVersionAttribute("11.4.1")>]
[<assembly: AssemblyFileVersionAttribute("11.4.1")>]
[<assembly: AssemblyInformationalVersionAttribute("11.4.1")>]
[<assembly: AssemblyCopyrightAttribute("Apache 2.0 License")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyProduct = "Fable.Formatting"
    let [<Literal>] AssemblyDescription = "A package of libraries for building great F# documentation, samples and blogs"
    let [<Literal>] AssemblyVersion = "11.4.1"
    let [<Literal>] AssemblyFileVersion = "11.4.1"
    let [<Literal>] AssemblyInformationalVersion = "11.4.1"
    let [<Literal>] AssemblyCopyright = "Apache 2.0 License"
